---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pco.plusserver.com
  resources:
  - projects
  - regions
  - userprojectbindings
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pco.plusserver.com
  resources:
  - projects/finalizers
  - regions/finalizers
  - userprojectbindings/finalizers
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - pco.plusserver.com
  resources:
  - projects/status
  - regions/status
  - userprojectbindings/status
  - users/status
  verbs:
  - get
  - patch
  - update
