/*
Copyright © 2023 PlusServer GmbH

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	"context"
	"errors"
	"fmt"

	"github.com/pluscontainer/pco-reseller-operator/internal/utils"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
)

// log is for logging in this package.
var projectlog = logf.Log.WithName("project-resource")

// SetupWebhookWithManager registers the webhook within the manager
func (r *Project) SetupWebhookWithManager(mgr ctrl.Manager) error {
	return ctrl.NewWebhookManagedBy(mgr).
		For(r).
		WithDefaulter(&ProjectCustomDefaulter{}).
		WithValidator(&ProjectCustomValidator{}).
		Complete()
}

//+kubebuilder:webhook:path=/mutate-pco-plusserver-com-v1alpha1-project,mutating=true,failurePolicy=fail,sideEffects=None,groups=pco.plusserver.com,resources=projects,verbs=create;update,versions=v1alpha1,name=mproject.kb.io,admissionReviewVersions=v1

type ProjectCustomDefaulter struct {
	// TODO(user): Add more fields as needed for validation
}

var _ webhook.CustomDefaulter = &ProjectCustomDefaulter{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (v *ProjectCustomDefaulter) Default(ctx context.Context, obj runtime.Object) error {
	project, ok := obj.(*Project)
	if !ok {
		return fmt.Errorf("expected a Project object but got %T", obj)
	}

	projectlog.Info("default", "name", project.Name)

	if utils.IsEmpty(project.Spec.Description) {
		project.Spec.Description = "Generated by PCO Reseller Operator"
	}

	if project.Spec.Quotas == nil {
		project.Spec.Quotas = &QuotaCollection{
			Compute: defaultComputeQuota(),
			Volume:  defaultStorageQuota(),
			Network: defaultNetworkQuota(),
		}
	}

	if project.Spec.Quotas.Compute == nil {
		project.Spec.Quotas.Compute = defaultComputeQuota()
	}
	if project.Spec.Quotas.Volume == nil {
		project.Spec.Quotas.Volume = defaultStorageQuota()
	}
	if project.Spec.Quotas.Network == nil {
		project.Spec.Quotas.Network = defaultNetworkQuota()
	}
	return nil
}

func defaultComputeQuota() *ComputeQuotas {
	return &ComputeQuotas{
		Instances:          64,
		Cores:              intPointer(64),
		FloatingIps:        intPointer(10),
		Ram:                intPointer(262144),
		KeyPairs:           500,
		SecurityGroups:     intPointer(500),
		SecurityGroupRules: intPointer(500),
		ServerGroups:       10,
		ServerGroupMembers: intPointer(15),
		MetadataItems:      100,
	}
}

func defaultStorageQuota() *VolumeQuotas {
	return &VolumeQuotas{
		Gigabytes:       intPointer(2000),
		Volumes:         500,
		Snapshots:       intPointer(99),
		Backups:         99,
		BackupGigabytes: 2000,
	}
}

func defaultNetworkQuota() *NetworkQuotas {
	return &NetworkQuotas{
		Floatingip:        intPointer(10),
		Network:           10,
		Router:            10,
		SecurityGroup:     500,
		SecurityGroupRule: 500,
		Subnet:            100,
	}
}

func intPointer(v int) *int {
	return &v
}

// TODO(user): change verbs to "verbs=create;update;delete" if you want to enable deletion validation.
//+kubebuilder:webhook:path=/validate-pco-plusserver-com-v1alpha1-project,mutating=false,failurePolicy=fail,sideEffects=None,groups=pco.plusserver.com,resources=projects,verbs=create;update,versions=v1alpha1,name=vproject.kb.io,admissionReviewVersions=v1

type ProjectCustomValidator struct {
	// TODO(user): Add more fields as needed for validation
}

var _ webhook.CustomValidator = &ProjectCustomValidator{}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (v *ProjectCustomValidator) ValidateCreate(ctx context.Context, obj runtime.Object) (admission.Warnings, error) {
	project, ok := obj.(*Project)
	if !ok {
		return nil, fmt.Errorf("expected a Project object but got %T", obj)
	}
	projectlog.Info("validate create", "name", project.Name)

	if utils.IsEmpty(project.Spec.Region) {
		return nil, errors.New(".spec.region must be specified")
	}

	return nil, nil
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (v *ProjectCustomValidator) ValidateUpdate(ctx context.Context, oldObj, newObj runtime.Object) (admission.Warnings, error) {
	oldProject, ok := oldObj.(*Project)
	if !ok {
		return nil, fmt.Errorf("expected a Project object but got %T", oldObj)
	}
	newProject, ok := newObj.(*Project)
	if !ok {
		return nil, fmt.Errorf("expected a Project object but got %T", newObj)
	}
	projectlog.Info("validate update", "name", oldProject.Name)

	if oldProject.Spec.Region != newProject.Spec.Region {
		return nil, errors.New("region field is immutable")
	}

	return nil, nil
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (v *ProjectCustomValidator) ValidateDelete(ctx context.Context, obj runtime.Object) (admission.Warnings, error) {
	project, ok := obj.(*Project)
	if !ok {
		return nil, fmt.Errorf("expected a Project object but got %T", obj)
	}
	projectlog.Info("validate delete", "name", project.Name)

	// TODO(user): fill in your validation logic upon object deletion.
	return nil, nil
}
