/*
Copyright © 2023 PlusServer GmbH

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	"context"
	"fmt"

	"github.com/pluscontainer/pco-reseller-operator/internal/utils"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
)

// log is for logging in this package.
var userlog = logf.Log.WithName("user-resource")

// SetupWebhookWithManager registers the webhook with the manager
func (r *User) SetupWebhookWithManager(mgr ctrl.Manager) error {
	return ctrl.NewWebhookManagedBy(mgr).
		For(r).
		WithDefaulter(&UserCustomDefaulter{}).
		WithValidator(&UserCustomValidator{}).
		Complete()
}

// TODO(user): EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!

// +kubebuilder:webhook:path=/mutate-pco-plusserver-com-v1alpha1-user,mutating=true,failurePolicy=fail,sideEffects=None,groups=pco.plusserver.com,resources=users,verbs=create;update,versions=v1alpha1,name=muser.kb.io,admissionReviewVersions=v1
type UserCustomDefaulter struct {
	// TODO(user): Add more fields as needed for validation
}

var _ webhook.CustomDefaulter = &UserCustomDefaulter{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (v *UserCustomDefaulter) Default(ctx context.Context, obj runtime.Object) error {
	user, ok := obj.(*User)
	if !ok {
		return fmt.Errorf("expected a User object but got %T", obj)
	}
	userlog.Info("default", "name", user.Name)

	if utils.IsEmpty(user.Spec.Description) {
		user.Spec.Description = "Generated by PCO Reseller Operator"
	}

	if user.Spec.Enabled == nil {
		isTrue := true
		user.Spec.Enabled = &isTrue
	}
	return nil
}

// TODO(user): change verbs to "verbs=create;update;delete" if you want to enable deletion validation.
//+kubebuilder:webhook:path=/validate-pco-plusserver-com-v1alpha1-user,mutating=false,failurePolicy=fail,sideEffects=None,groups=pco.plusserver.com,resources=users,verbs=create;update,versions=v1alpha1,name=vuser.kb.io,admissionReviewVersions=v1

type UserCustomValidator struct {
	// TODO(user): Add more fields as needed for validation
}

var _ webhook.CustomValidator = &UserCustomValidator{}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (v *UserCustomValidator) ValidateCreate(ctx context.Context, obj runtime.Object) (admission.Warnings, error) {
	user, ok := obj.(*User)
	if !ok {
		return nil, fmt.Errorf("expected a User object but got %T", obj)
	}
	userlog.Info("validate create", "name", user.Name)

	return nil, nil
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (v *UserCustomValidator) ValidateUpdate(ctx context.Context, newObj runtime.Object, oldObj runtime.Object) (admission.Warnings, error) {
	user, ok := oldObj.(*User)
	if !ok {
		return nil, fmt.Errorf("expected a User object but got %T", oldObj)
	}
	userlog.Info("validate update", "name", user.Name)

	//All currently defined fields are mutable
	return nil, nil
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (v *UserCustomValidator) ValidateDelete(ctx context.Context, obj runtime.Object) (admission.Warnings, error) {
	user, ok := obj.(*User)
	if !ok {
		return nil, fmt.Errorf("expected a User object but got %T", obj)
	}
	userlog.Info("validate delete", "name", user.Name)

	// TODO(user): fill in your validation logic upon object deletion.
	return nil, nil
}
